version: '3'

services:
  emqx:
    image: emqx/emqx:5.8
    restart: always
    container_name: emqx
    ports:
      - 2883:1883
      - 28083:18083
    volumes:
      - ./data:/opt/emqx/data
      - ./config:/opt/emqx/etc
      - ./log:/opt/emqx/log