# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
        # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this config.
        labels:
          app: "prometheus"

  - job_name: "alloy"
    static_configs:
      - targets: ["alloy:12345"]
        labels:
          app: alloy

  # - job_name: "node_exporter"
  #   static_configs:
  #     - targets: ["<ip>:9100"]
  #       labels:
  #         app: "node_exporter"

  # - job_name: "cadvisor"
  #   static_configs:
  #     - targets: [<ip>:18080]
  #       labels:
  #         app: "cadvisor"

  # - job_name: "mysql"
  #   static_configs:
  #     - targets:
  #         - "<ip>:9104"
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance

  # - job_name: "postgres"
  #   static_configs:
  #     - targets:
  #         - "<ip>:9187"
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: <postgres-host>

  # - job_name: "redis"
  #   static_configs:
  #     - targets:
  #         - "<ip>:9121"
  #   metrics_path: /scrape
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: <redis-host>

  # - job_name: "emqx"
  #   static_configs:
  #     - targets:
  #         - "<ip>:18083"
  #   metrics_path: "/api/v5/prometheus/stats"
  #   scheme: "http"
  #   basic_auth:
  #     username: "<user>"
  #     password: "<password>"

  # - job_name: "emqx_auth"
  #   static_configs:
  #     - targets:
  #         - <ip>:18083
  #   metrics_path: "/api/v5/prometheus/auth"
  #   scheme: "http"
  #   basic_auth:
  #     username: "<user>"
  #     password: "<password>"

  # - job_name: "emqx_data_integration"
  #   static_configs:
  #     - targets:
  #         - "<ip>:18083"
  #   metrics_path: "/api/v5/prometheus/data_integration"
  #   scheme: "http"
  #   basic_auth:
  #     username: "<user>"
  #     password: "<password>"
