services:
  mysql-exporter:
    profiles:
      - MYSQL_EXPORTER
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    restart: always
    ports:
      - 9104:9104
    volumes:
      - ./config.cnf:/.my.cnf:ro
    environment:
      - TZ=Asia/Shanghai
    networks:
      - monitor-net
